### PR TITLE
rename namespace from spin to lo

### PR DESCRIPTION
**Pull request by ayushmanchhabra**
This PR changes the internal namespace from `spin` to `lo`. From what I understand, `lo` is the name of the runtime while `spin` is the name of the `GLOBALOBJ` macro which can be changed by whoever is using it to build a higher level runtime on top of `lo`.

### CODE REVIEW

**Comment by billywhizz** [comment]
thanks for this @ayushmanchhabra. :pray:  i was thinking on this earlier and kinda felt it would be better to change the C++ namespace to "runtime". so we would use "runtime" everywhere we use "spin" in this PR. 

but the global object on the JS could be set to "lo". that way embedders that want to use this in modules/bindings could just use the generic "runtime" namespace in C++ but use a completely different name for their global JS object if they wanted to. what do you think?

i'll probably accept this PR as it is regardless for now but need to look at a few other things first.

**Comment by ayushmanchhabra** [comment]
Sounds good to me! I can change `spin` to `runtime` in this PR itself.

**Comment by billywhizz** [comment]
> Sounds good to me! I can change ~`spin`~ `lo` to `runtime` in this PR itself.

hold off for now. i think we will just go with this PR. thanks again for submitting! :pray:

**Review by billywhizz — APPROVED** [review]
lgtm

**Pull request merged**
